# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: JfrogCliV2@1
  inputs:
    jfrogPlatformConnection: 'psemea'
    command: |
      jf c s
      jf mvnc  --repo-deploy-releases demo-nn-libs-release
      jf mvnc  --repo-deploy-snapshots demo-nn-libs-snapshot-local
      jf mvnc  --repo-resolve-releases maven-remote
      jf mvnc  --repo-resolve-snapshots maven-remote

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    jf c s
  displayName: 'Run a multi-line script'
